[package]
name = "container-debug"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive", "env"] }
clap_complete = "4.5.33"
env_logger = "0.11.8"
log = "0.4.27"

[workspace.lints.clippy]
unwrap_used = "deny"
